---
steps:
  - label: ':bazel: Build & Test'
    commands:
      - bazel build --config=ci //src/main/...
      - bazel test --config=ci //src/test/...
    branches: "!main"

  - label: ':bazel: Test & Coverage'
    commands:
      - bazel coverage --config=ci //src/test/...
    branches: "main"
    key: "coverage"

  - group: ":trollface: Upload Coverage"
    steps:
      - label: ':codecov: Upload to Codecov'
        commands:
          - codecov -f "$(bazel info output_path)/_coverage/_coverage_report.dat"
        branches: "main"

      - label: ':codeclimate: Upload to Code Climate'
        commands:
          - cc-test-reporter format-coverage -t lcov -o .coverage/codeclimate.json
            "$(bazel info output_path)/_coverage/_coverage_report.dat"
          - cc-test-reporter upload-coverage -r "$CC_TEST_REPORTER_ID" -i .coverage/codeclimate.json
        branches: "main"

    depends_on: "coverage"
