#load("@rules_java//java:defs.bzl", "java_library", "java_test")

#java_library(
#    name = "tests",
#    testonly = True,
#    srcs = glob(["*.java"]),
#    deps = [
#        "//src/main/kotlin/com/fillmore_labs/talk/value/simple/kotlin",
#        "//toolchain:nullaway",
#        "//toolchain:truth",
#        "@com_github_jetbrains_kotlin//:kotlin-stdlib",
#       #        "@maven//:com_google_guava_guava",
#    ],
#)

#java_test(
#    name = "EmailAddressTest",
#    size = "small",
#    runtime_deps = [
#        ":tests",
#    ],
#)

#java_test(
#    name = "PersonTest",
#    size = "small",
#    runtime_deps = [
#        ":tests",
#    ],
#)
